"""add email drafts

Revision ID: 048830c765b7
Revises: a9a50beaed89
Create Date: 2026-10-04 02:31:48.842291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048830c765b7'
down_revision: Union[str, Sequence[str], None] = 'a9a50beaed89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_email_id'), 'email_drafts', ['email_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_id'), 'email_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_email_drafts_workflow_run_id'), 'email_drafts', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_drafts_workflow_run_id'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_id'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_email_id'), table_name='email_drafts')
    op.drop_table('email_drafts')
    # ### end Alembic commands ###
