"""create email accounts table

Revision ID: 361f9c8ca8f9
Revises: 38f9f141453b
Create Date: 2026-10-02 21:23:41.705040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361f9c8ca8f9'
down_revision: Union[str, Sequence[str], None] = '38f9f141453b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('provider', sa.Enum('GMAIL', name='emailprovider'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_accounts_email_address'), 'email_accounts', ['email_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_accounts_email_address'), table_name='email_accounts')
    op.drop_table('email_accounts')
    # ### end Alembic commands ###
