"""add sent fields to email drafts

Revision ID: 89bc35724746
Revises: e15f3eaf2227
Create Date: 2026-10-04 03:20:31.013776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bc35724746'
down_revision: Union[str, Sequence[str], None] = 'e15f3eaf2227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_drafts', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('email_drafts', sa.Column('provider_message_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_drafts', 'provider_message_id')
    op.drop_column('email_drafts', 'sent_at')
    # ### end Alembic commands ###
