"""add sales lead extractions

Revision ID: 91eeba9ba32b
Revises: d786b22a993c
Create Date: 2026-10-03 22:41:49.693490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91eeba9ba32b'
down_revision: Union[str, Sequence[str], None] = 'd786b22a993c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_lead_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('product_interest', sa.Text(), nullable=True),
    sa.Column('budget', sa.String(length=255), nullable=True),
    sa.Column('timeline', sa.String(length=255), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_lead_extractions_email_id'), 'sales_lead_extractions', ['email_id'], unique=True)
    op.create_index(op.f('ix_sales_lead_extractions_id'), 'sales_lead_extractions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_lead_extractions_id'), table_name='sales_lead_extractions')
    op.drop_index(op.f('ix_sales_lead_extractions_email_id'), table_name='sales_lead_extractions')
    op.drop_table('sales_lead_extractions')
    # ### end Alembic commands ###
