"""add workflow action definitions

Revision ID: a9a50beaed89
Revises: 5e12b142fcae
Create Date: 2026-10-04 02:24:42.686909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a50beaed89'
down_revision: Union[str, Sequence[str], None] = '5e12b142fcae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_action_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_action_definitions_id'), 'workflow_action_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_action_definitions_workflow_id'), 'workflow_action_definitions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_action_definitions_workflow_id'), table_name='workflow_action_definitions')
    op.drop_index(op.f('ix_workflow_action_definitions_id'), table_name='workflow_action_definitions')
    op.drop_table('workflow_action_definitions')
    # ### end Alembic commands ###
