"""add email classifications

Revision ID: d786b22a993c
Revises: 36f019e20dd8
Create Date: 2026-10-03 22:24:09.229202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd786b22a993c'
down_revision: Union[str, Sequence[str], None] = '36f019e20dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('SALES_LEAD', 'CUSTOMER_SUPPORT', 'INVOICE', 'QUOTATION', 'APPOINTMENT', 'APPLICATION', 'COMPLAINT', 'GENERAL_ENQUIRY', 'INTERNAL', 'SPAM', 'OTHER', name='emailcategory'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('urgency', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_classifications_email_id'), 'email_classifications', ['email_id'], unique=True)
    op.create_index(op.f('ix_email_classifications_id'), 'email_classifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_classifications_id'), table_name='email_classifications')
    op.drop_index(op.f('ix_email_classifications_email_id'), table_name='email_classifications')
    op.drop_table('email_classifications')
    # ### end Alembic commands ###
