"""add draft review fields

Revision ID: e15f3eaf2227
Revises: 048830c765b7
Create Date: 2026-10-04 02:39:47.924534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15f3eaf2227'
down_revision: Union[str, Sequence[str], None] = '048830c765b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_drafts', sa.Column('reviewed_by', sa.String(length=255), nullable=True))
    op.add_column('email_drafts', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_drafts', 'reviewed_at')
    op.drop_column('email_drafts', 'reviewed_by')
    # ### end Alembic commands ###
